# Generated by Django 3.1.2 on 2020-10-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20201022_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
