# Generated by Django 3.1.2 on 2020-10-21 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_days', models.IntegerField(blank=True, null=True)),
                ('penalty_fee', models.FloatField(blank=True, null=True)),
                ('interest_per_day', models.FloatField(blank=True, null=True)),
                ('total_paid', models.FloatField(blank=True, null=True)),
                ('paid_out', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan', to='loan.loan')),
            ],
        ),
    ]
