# Generated by Django 3.1.2 on 2020-10-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penalty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penalty',
            name='interest_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='paid_out',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='penalty_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='total_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
