# Generated by Django 3.1.2 on 2020-10-23 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
        ('penalty', '0002_auto_20201023_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penalty',
            name='loan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='penalty', to='loan.loan'),
        ),
    ]
