# Generated by Django 3.1.2 on 2020-10-24 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penalty', '0003_auto_20201023_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penalty',
            name='paid_out',
        ),
    ]
