# Generated by Django 3.1.2 on 2020-10-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penalty', '0004_remove_penalty_paid_out'),
    ]

    operations = [
        migrations.RenameField(
            model_name='penalty',
            old_name='number_days',
            new_name='delayed_days',
        ),
        migrations.AddField(
            model_name='penalty',
            name='fine_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
