# Generated by Django 3.1.2 on 2020-10-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_reservation',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_reservation_final',
            field=models.DateField(null=True),
        ),
    ]
